package gui;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.Admin;
import service.Database;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ashik
 */
public class AdminSignupFrame extends javax.swing.JFrame {
    
    private final Database database;
    private Admin admin;

    /**
     * Creates new form AdminSignupFrame
     *
     * @param database
     */
    public AdminSignupFrame(Database database) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        this.initComponents();
        
        this.database = database;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lMessage = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        tfRetypePassword = new javax.swing.JPasswordField();
        tfMasterUsername = new javax.swing.JTextField();
        tfMasterPassword = new javax.swing.JPasswordField();
        bReset = new javax.swing.JButton();
        bSignup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Signup");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Inventory Management System");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Admin Signup");

        lMessage.setText("Please insert all fields correctly to create a new admin");

        tfUsername.setToolTipText("New Admin Username");

        tfEmail.setToolTipText("Admin E-Mail ID");

        tfPassword.setToolTipText("Type Password");

        tfRetypePassword.setToolTipText("Re-Type Password");

        tfMasterUsername.setToolTipText("Master Username");

        tfMasterPassword.setToolTipText("Master Password");

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bSignup.setText("Signup");
        bSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignupActionPerformed(evt);
            }
        });

        jLabel4.setText("Username : ");

        jLabel5.setText("E-Mail : ");

        jLabel6.setText("Password : ");

        jLabel7.setText("Re-Type Password : ");

        jLabel8.setText("Master Username : ");

        jLabel9.setText("Master Password : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPassword)
                            .addComponent(tfEmail)
                            .addComponent(tfUsername)
                            .addComponent(tfRetypePassword, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(879, 879, 879))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(bSignup))
                    .addComponent(tfMasterPassword)
                    .addComponent(tfMasterUsername))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bReset, bSignup});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lMessage)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMasterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMasterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReset)
                    .addComponent(bSignup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        
        try {
            
            this.balanceColor();
            
            this.tfEmail.setText(null);
            this.tfMasterPassword.setText(null);
            this.tfMasterUsername.setText(null);
            this.tfPassword.setText(null);
            this.tfRetypePassword.setText(null);
            this.tfUsername.setText(null);
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_bResetActionPerformed

    private void bSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignupActionPerformed
        
        try {
            
            if (this.checkFields()) {
                
                this.admin = new Admin(this.tfUsername.getText().trim(), this.tfPassword.getText(), this.tfEmail.getText(), "admin");
                if (this.database.insertNewAdmin(this.admin)) {
                    
                    JOptionPane.showMessageDialog(this, "Success!");
                    this.dispose();
                }
            }
        } catch (HeadlessException e) {
            
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_bSignupActionPerformed
    
    private boolean checkFields() {
        
        boolean isOk = true;
        
        this.balanceColor();
        
        try {
            
            if (this.tfEmail.getText().trim().equals("")) {
                
                this.tfEmail.setText(null);
                this.tfEmail.setBackground(Color.yellow);
                isOk = false;
            }
            if (this.tfMasterPassword.getText().trim().equals("")) {
                
                this.tfMasterPassword.setText(null);
                this.tfMasterPassword.setBackground(Color.yellow);
                isOk = false;
            }
            if (this.tfMasterUsername.getText().trim().equals("")) {
                
                this.tfMasterUsername.setText(null);
                this.tfMasterUsername.setBackground(Color.yellow);
                isOk = false;
            }
            if (this.tfPassword.getText().trim().equals("")) {
                
                this.tfPassword.setText(null);
                this.tfPassword.setBackground(Color.yellow);
                isOk = false;
            }
            if (this.tfRetypePassword.getText().trim().equals("")) {
                
                this.tfRetypePassword.setText(null);
                this.tfRetypePassword.setBackground(Color.yellow);
                isOk = false;
            }
            if (this.tfUsername.getText().trim().equals("")) {
                
                this.tfUsername.setText(null);
                this.tfUsername.setBackground(Color.yellow);
                isOk = false;
            }
            if (!this.tfPassword.getText().equals(this.tfRetypePassword.getText())) {
                
                this.tfPassword.setFocusable(true);
                this.tfRetypePassword.setFocusable(true);
                isOk = false;
                this.lMessage.setText("Password doesn't match! Please try again.");
            }
            
            this.admin = this.database.selectMasterAdmin();
            
            if (this.admin == null || !this.admin.getUsername().equals(this.tfMasterUsername.getText()) || !this.admin.getPassword().equals(this.tfMasterPassword.getText())) {
                
                this.tfMasterUsername.setFocusable(true);
                this.tfMasterPassword.setFocusable(true);
                isOk = false;
                this.lMessage.setText("Master username and password is not correct! Please try again.");
            }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e);
        }
        
        return isOk;
    }
    
    private void balanceColor() {
        
        try {
            
            this.tfEmail.setBackground(Color.white);
            this.tfMasterPassword.setBackground(Color.white);
            this.tfMasterUsername.setBackground(Color.white);
            this.tfPassword.setBackground(Color.white);
            this.tfRetypePassword.setBackground(Color.white);
            this.tfUsername.setBackground(Color.white);
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lMessage;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfMasterPassword;
    private javax.swing.JTextField tfMasterUsername;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JPasswordField tfRetypePassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
